# Generated by Django 3.1.12 on 2025-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('pub_data', models.DateTimeField(verbose_name='Published on')),
                ('posted_by', models.CharField(max_length=100)),
            ],
        ),
    ]
