# Generated by Django 3.1.12 on 2025-02-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
