# Generated by Django 3.1.12 on 2025-02-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0002_auto_20250216_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_desc',
            field=models.TextField(default='Sample Job description'),
            preserve_default=False,
        ),
    ]
